% Copyright (C) David Moreno Gallego de la Sacristana, 2023
% david.moreno.gs@gmail.com
% -----------------------------------------------------------
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to use
% the Software for non-commercial purposes only. Any distribution of the
% Software or modifications thereof is strictly prohibited without written
% consent from the author.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.
% 
% For commercial use or distribution, please contact the author.

function [] = CreateCylinder(name,component,ro,ri,axis,h,xc,yc,material)
global mws;

if (axis == 'x')
    mws.invoke('AddToHistory', [name 'Creation'],[...
    sprintf('With Cylinder\n') ...
    sprintf('  .Reset\n') ...
    sprintf(['  .Name "' name '"\n']) ...
    sprintf(['  .Component "' component '"\n']) ... 
    sprintf(['  .Material "' material '"\n']) ... 
    sprintf(['  .OuterRadius "' num2str(ro) '"\n']) ...
    sprintf(['  .InnerRadius "' num2str(ri) '"\n']) ...
    sprintf(['  .Axis "' axis '"\n']) ...
    sprintf(['  .Xrange "' num2str(h(1)) '", "' num2str(h(2)) '"\n']) ...
    sprintf(['  .Ycenter "' num2str(yc) '"\n']) ...
    sprintf(['  .Zcenter "' num2str(zc) '"\n']) ...
    sprintf(['  .Segments "0"\n']) ...
    sprintf(' .Create\n') ...
    sprintf('End With')]);
elseif axis == 'y'
    mws.invoke('AddToHistory', [name 'Creation'],[...
    sprintf('With Cylinder\n') ...
    sprintf('  .Reset\n') ...
    sprintf(['  .Name "' name '"\n']) ...
    sprintf(['  .Component "' component '"\n']) ... 
    sprintf(['  .Material "' material '"\n']) ... 
    sprintf(['  .OuterRadius "' num2str(ro) '"\n']) ...
    sprintf(['  .InnerRadius "' num2str(ri) '"\n']) ...
    sprintf(['  .Axis "' axis '"\n']) ...
    sprintf(['  .Yrange "' num2str(h(1)) '", "' num2str(h(2)) '"\n']) ...
    sprintf(['  .Xcenter "' num2str(xc) '"\n']) ...
    sprintf(['  .Zcenter "' num2str(zc) '"\n']) ...
    sprintf(['  .Segments "0"\n']) ...
    sprintf(' .Create\n') ...
    sprintf('End With')]);
else
    mws.invoke('AddToHistory', [name 'Creation'],[...
    sprintf('With Cylinder\n') ...
    sprintf('  .Reset\n') ...
    sprintf(['  .Name "' name '"\n']) ...
    sprintf(['  .Component "' component '"\n']) ... 
    sprintf(['  .Material "' material '"\n']) ... 
    sprintf(['  .OuterRadius "' num2str(ro) '"\n']) ...
    sprintf(['  .InnerRadius "' num2str(ri) '"\n']) ...
    sprintf(['  .Axis "' axis '"\n']) ...
    sprintf(['  .Zrange "' num2str(h(1)) '", "' num2str(h(2)) '"\n']) ...
    sprintf(['  .Xcenter "' num2str(xc) '"\n']) ...
    sprintf(['  .Ycenter "' num2str(yc) '"\n']) ...
    sprintf(['  .Segments "0"\n']) ...
    sprintf(' .Create\n') ...
    sprintf('End With')]);
end


end